env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 15
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {}
