
<Structures>
  <Structure Name="Building" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" Description="sprite_selection?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4" Vartype="4 Bytes" Bytesize="4" Description="sprite_category?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="12" Vartype="Array of byte" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="16" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="20" Vartype="4 Bytes" Bytesize="4" Description="some_time_counter_1" DisplayMethod="Unsigned Integer"/>
      <Element Offset="24" Vartype="4 Bytes" Bytesize="4" Description="some_time_counter_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="28" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="32" Vartype="2 Bytes" Bytesize="2" Description="some_timer_3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="34" Vartype="2 Bytes" Bytesize="2" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="40" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="44" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="48" Vartype="4 Bytes" Bytesize="4" Description="starts_blinking_when_building_selected" DisplayMethod="Unsigned Integer"/>
      <Element Offset="52" Vartype="4 Bytes" Bytesize="4" RLECount="22" DisplayMethod="Unsigned Integer"/>
      <Element Offset="140" Vartype="4 Bytes" Bytesize="4" Description="last_location_tile_index?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="144" Vartype="4 Bytes" Bytesize="4" Description="some_kind_of_counter_tied_to_timer_resets" DisplayMethod="Unsigned Integer"/>
      <Element Offset="148" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="152" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="156" Vartype="4 Bytes" Bytesize="4" RLECount="9" DisplayMethod="Unsigned Integer"/>
      <Element Offset="192" Vartype="4 Bytes" Bytesize="4" Description="timer_gamespeed_relative_resets_after_0x100" DisplayMethod="Unsigned Integer"/>
      <Element Offset="196" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="200" Vartype="4 Bytes" Bytesize="4" Description="some_kind_of_tile_index?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="204" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="206" Vartype="Byte" Bytesize="1" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="208" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="210" Vartype="4 Bytes" Bytesize="4" Description="building_type_id" DisplayMethod="Unsigned Integer"/>
      <Element Offset="214" Vartype="2 Bytes" Bytesize="2" Description="owner" DisplayMethod="Unsigned Integer"/>
      <Element Offset="216" Vartype="2 Bytes" Bytesize="2" Description="building_uid" DisplayMethod="Unsigned Integer"/>
      <Element Offset="218" Vartype="Byte" Bytesize="1" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="220" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="232" Vartype="Byte" Bytesize="1" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="236" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="238" Vartype="2 Bytes" Bytesize="2" Description="location_j_serialized_adjusted" DisplayMethod="Unsigned Integer"/>
      <Element Offset="240" Vartype="2 Bytes" Bytesize="2" Description="location_i_serialized" DisplayMethod="Unsigned Integer"/>
      <Element Offset="242" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="244" Vartype="2 Bytes" Bytesize="2" Description="location_serialized_tile_index_adjusted" DisplayMethod="Signed Integer"/>
      <Element Offset="246" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="248" Vartype="4 Bytes" Bytesize="4" Description="width_or_height" DisplayMethod="Unsigned Integer"/>
      <Element Offset="252" Vartype="2 Bytes" Bytesize="2" Description="width_or_height_times_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="254" Vartype="2 Bytes" Bytesize="2" Description="location_j_serialized_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="256" Vartype="2 Bytes" Bytesize="2" Description="location_i_serialized_plus_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="258" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="260" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="268" Vartype="2 Bytes" Bytesize="2" Description="health" DisplayMethod="Unsigned Integer"/>
      <Element Offset="270" Vartype="2 Bytes" Bytesize="2" Description="hitpoints" DisplayMethod="Unsigned Integer"/>
      <Element Offset="272" Vartype="4 Bytes" Bytesize="4" RLECount="6" DisplayMethod="Unsigned Integer"/>
      <Element Offset="296" Vartype="4 Bytes" Bytesize="4" Description="stockpile_wood" DisplayMethod="Unsigned Integer"/>
      <Element Offset="300" Vartype="4 Bytes" Bytesize="4" Description="stockpile_hops" DisplayMethod="Unsigned Integer"/>
      <Element Offset="304" Vartype="4 Bytes" Bytesize="4" Description="stockpile_stone" DisplayMethod="Unsigned Integer"/>
      <Element Offset="308" Vartype="4 Bytes" Bytesize="4" Description="stockpile_partialstone" DisplayMethod="Unsigned Integer"/>
      <Element Offset="312" Vartype="4 Bytes" Bytesize="4" Description="stockpile_iron" DisplayMethod="Unsigned Integer"/>
      <Element Offset="316" Vartype="4 Bytes" Bytesize="4" Description="stockpile_pitch" DisplayMethod="Unsigned Integer"/>
      <Element Offset="320" Vartype="4 Bytes" Bytesize="4" Description="stockpile_partialpitch" DisplayMethod="Unsigned Integer"/>
      <Element Offset="324" Vartype="4 Bytes" Bytesize="4" Description="stockpile_wheat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="328" Vartype="4 Bytes" Bytesize="4" Description="stockpile_bread" DisplayMethod="Unsigned Integer"/>
      <Element Offset="332" Vartype="4 Bytes" Bytesize="4" Description="stockpile_cheese" DisplayMethod="Unsigned Integer"/>
      <Element Offset="336" Vartype="4 Bytes" Bytesize="4" Description="stockpile_meat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="340" Vartype="4 Bytes" Bytesize="4" Description="stockpile_apple" DisplayMethod="Unsigned Integer"/>
      <Element Offset="344" Vartype="4 Bytes" Bytesize="4" Description="stockpile_ale" DisplayMethod="Unsigned Integer"/>
      <Element Offset="348" Vartype="4 Bytes" Bytesize="4" Description="stockpile_gold" DisplayMethod="Unsigned Integer"/>
      <Element Offset="352" Vartype="4 Bytes" Bytesize="4" Description="stockpile_flour" DisplayMethod="Unsigned Integer"/>
      <Element Offset="356" Vartype="4 Bytes" Bytesize="4" Description="stockpile_bow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="360" Vartype="4 Bytes" Bytesize="4" Description="stockpile_crossbow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="364" Vartype="4 Bytes" Bytesize="4" Description="stockpile_spear" DisplayMethod="Unsigned Integer"/>
      <Element Offset="368" Vartype="4 Bytes" Bytesize="4" Description="stockpile_pike" DisplayMethod="Unsigned Integer"/>
      <Element Offset="372" Vartype="4 Bytes" Bytesize="4" Description="stockpile_mace" DisplayMethod="Unsigned Integer"/>
      <Element Offset="376" Vartype="4 Bytes" Bytesize="4" Description="stockpile_sword" DisplayMethod="Unsigned Integer"/>
      <Element Offset="380" Vartype="4 Bytes" Bytesize="4" Description="stockpile_leather_armor" DisplayMethod="Unsigned Integer"/>
      <Element Offset="384" Vartype="4 Bytes" Bytesize="4" Description="stockpile_iron_armor" DisplayMethod="Unsigned Integer"/>
      <Element Offset="388" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="400" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="402" Vartype="2 Bytes" Bytesize="2" Description="building_id_stone_quarry_stockpile" DisplayMethod="Unsigned Integer"/>
      <Element Offset="404" Vartype="2 Bytes" Bytesize="2" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="410" Vartype="2 Bytes" Bytesize="2" Description="current_employees_count" DisplayMethod="Unsigned Integer"/>
      <Element Offset="412" Vartype="2 Bytes" Bytesize="2" Description="employees_still_needed" DisplayMethod="Unsigned Integer"/>
      <Element Offset="414" Vartype="2 Bytes" Bytesize="2" Description="worker_id" DisplayMethod="Unsigned Integer"/>
      <Element Offset="416" Vartype="2 Bytes" Bytesize="2" Description="peasant_recruitment_timer?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="418" Vartype="2 Bytes" Bytesize="2" Description="peasant_recruitment_timer_2?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="420" Vartype="4 Bytes" Bytesize="4" RLECount="9" DisplayMethod="Unsigned Integer"/>
      <Element Offset="456" Vartype="4 Bytes" Bytesize="4" Description="location0_serialized_tile_index_only_if_non_passible" DisplayMethod="Unsigned Integer"/>
      <Element Offset="460" Vartype="4 Bytes" Bytesize="4" Description="location1" DisplayMethod="Signed Integer"/>
      <Element Offset="464" Vartype="4 Bytes" Bytesize="4" Description="location2" DisplayMethod="Signed Integer"/>
      <Element Offset="468" Vartype="4 Bytes" Bytesize="4" Description="location3" DisplayMethod="Signed Integer"/>
      <Element Offset="472" Vartype="4 Bytes" Bytesize="4" RLECount="31" DisplayMethod="Unsigned Integer"/>
      <Element Offset="596" Vartype="4 Bytes" Bytesize="4" Description="location_35_serialized_index_max" DisplayMethod="Unsigned Integer"/>
      <Element Offset="600" Vartype="4 Bytes" Bytesize="4" RLECount="9" DisplayMethod="Unsigned Integer"/>
      <Element Offset="636" Vartype="4 Bytes" Bytesize="4" Description="time_in_existence" DisplayMethod="Signed Integer"/>
      <Element Offset="640" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="644" Vartype="4 Bytes" Bytesize="4" Description="building_subtype_ie_house" DisplayMethod="Unsigned Integer"/>
      <Element Offset="648" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="656" Vartype="2 Bytes" Bytesize="2" Description="produced_item_id" DisplayMethod="Unsigned Integer"/>
      <Element Offset="658" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="662" Vartype="Byte" Bytesize="1" Description="sleeping" DisplayMethod="Unsigned Integer"/>
      <Element Offset="663" Vartype="Byte" Bytesize="1" Description="n_horses" DisplayMethod="Unsigned Integer"/>
      <Element Offset="664" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="668" Vartype="4 Bytes" Bytesize="4" Description="subtype_or_skin?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="672" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="676" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="678" Vartype="Byte" Bytesize="1" DisplayMethod="Unsigned Integer"/>
      <Element Offset="679" Vartype="Byte" Bytesize="1" Description="n_horses_in_use" DisplayMethod="Unsigned Integer"/>
      <Element Offset="680" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="696" Vartype="2 Bytes" Bytesize="2" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="702" Vartype="2 Bytes" Bytesize="2" Description="fire_duration_count_up_until_0" DisplayMethod="Unsigned Integer"/>
      <Element Offset="704" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="708" Vartype="4 Bytes" Bytesize="4" Description="cooldown_timer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="712" Vartype="4 Bytes" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="732" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="734" Vartype="2 Bytes" Bytesize="2" Description="fire_then_4_else_0" DisplayMethod="Unsigned Integer"/>
      <Element Offset="736" Vartype="4 Bytes" Bytesize="4" RLECount="19" DisplayMethod="Unsigned Integer"/>
    </Elements>
  </Structure>
</Structures>