
<Structures>
  <Structure Name="PlayerData" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" RLECount="6" DisplayMethod="Unsigned Integer"/>
      <Element Offset="24" Vartype="Byte" Bytesize="1" Description="rations_duplicate" DisplayMethod="Unsigned Integer"/>
      <Element Offset="25" Vartype="Byte" Bytesize="1" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="28" Vartype="4 Bytes" Bytesize="4" RLECount="17" DisplayMethod="Unsigned Integer"/>
      <Element Offset="96" Vartype="4 Bytes" Bytesize="4" Description="popularity" DisplayMethod="Unsigned Integer"/>
      <Element Offset="100" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="116" Vartype="4 Bytes" Bytesize="4" Description="population_cap" DisplayMethod="Unsigned Integer"/>
      <Element Offset="120" Vartype="4 Bytes" Bytesize="4" Description="current_population_duplicate" DisplayMethod="Unsigned Integer"/>
      <Element Offset="124" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="136" Vartype="4 Bytes" Bytesize="4" Description="available_peasants_at_fire" DisplayMethod="Unsigned Integer"/>
      <Element Offset="140" Vartype="4 Bytes" Bytesize="4" Description="available_peasants" DisplayMethod="Unsigned Integer"/>
      <Element Offset="144" Vartype="4 Bytes" Bytesize="4" RLECount="201" DisplayMethod="Unsigned Integer"/>
      <Element Offset="948" Vartype="4 Bytes" Bytesize="4" Description="previous_popularity?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="952" Vartype="4 Bytes" Bytesize="4" Description="army_size" DisplayMethod="Unsigned Integer"/>
      <Element Offset="956" Vartype="4 Bytes" Bytesize="4" RLECount="35" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1096" Vartype="4 Bytes" Bytesize="4" Description="gold_previous_month?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1100" Vartype="4 Bytes" Bytesize="4" RLECount="10" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1140" Vartype="4 Bytes" Bytesize="4" Description="starting_count_wood" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1144" Vartype="4 Bytes" Bytesize="4" Description="starting_count_hops" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1148" Vartype="4 Bytes" Bytesize="4" Description="starting_count_stone" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1152" Vartype="4 Bytes" Bytesize="4" Description="starting_count_good5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1156" Vartype="4 Bytes" Bytesize="4" Description="starting_count_iron" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1160" Vartype="4 Bytes" Bytesize="4" Description="starting_count_pitch" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1164" Vartype="4 Bytes" Bytesize="4" Description="starting_count_good8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1168" Vartype="4 Bytes" Bytesize="4" Description="starting_count_wheat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1172" Vartype="4 Bytes" Bytesize="4" Description="starting_count_bread" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1176" Vartype="4 Bytes" Bytesize="4" Description="starting_count_cheese" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1180" Vartype="4 Bytes" Bytesize="4" Description="starting_count_meat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1184" Vartype="4 Bytes" Bytesize="4" Description="starting_count_fruit" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1188" Vartype="4 Bytes" Bytesize="4" Description="starting_count_beer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1192" Vartype="4 Bytes" Bytesize="4" Description="starting_gold" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1196" Vartype="4 Bytes" Bytesize="4" Description="starting_count_flour" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1200" Vartype="4 Bytes" Bytesize="4" Description="starting_count_bow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1204" Vartype="4 Bytes" Bytesize="4" Description="starting_count_xbow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1208" Vartype="4 Bytes" Bytesize="4" Description="starting_count_spear" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1212" Vartype="4 Bytes" Bytesize="4" Description="starting_count_pike" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1216" Vartype="4 Bytes" Bytesize="4" Description="starting_count_mace" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1220" Vartype="4 Bytes" Bytesize="4" Description="starting_count_sword" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1224" Vartype="4 Bytes" Bytesize="4" Description="starting_count_leather" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1228" Vartype="4 Bytes" Bytesize="4" Description="starting_count_armor" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1232" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1240" Vartype="4 Bytes" Bytesize="4" Description="count_wood" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1244" Vartype="4 Bytes" Bytesize="4" Description="count_hops" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1248" Vartype="4 Bytes" Bytesize="4" Description="count_stone" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1252" Vartype="4 Bytes" Bytesize="4" Description="count_good5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1256" Vartype="4 Bytes" Bytesize="4" Description="count_iron" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1260" Vartype="4 Bytes" Bytesize="4" Description="count_pitch" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1264" Vartype="4 Bytes" Bytesize="4" Description="count_good8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1268" Vartype="4 Bytes" Bytesize="4" Description="count_wheat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1272" Vartype="4 Bytes" Bytesize="4" Description="count_bread" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1276" Vartype="4 Bytes" Bytesize="4" Description="count_cheese" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1280" Vartype="4 Bytes" Bytesize="4" Description="count_meat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1284" Vartype="4 Bytes" Bytesize="4" Description="count_fruit" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1288" Vartype="4 Bytes" Bytesize="4" Description="count_beer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1292" Vartype="4 Bytes" Bytesize="4" Description="gold" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1296" Vartype="4 Bytes" Bytesize="4" Description="count_flour" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1300" Vartype="4 Bytes" Bytesize="4" Description="count_bow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1304" Vartype="4 Bytes" Bytesize="4" Description="count_xbow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1308" Vartype="4 Bytes" Bytesize="4" Description="count_spear" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1312" Vartype="4 Bytes" Bytesize="4" Description="count_pike" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1316" Vartype="4 Bytes" Bytesize="4" Description="count_mace" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1320" Vartype="4 Bytes" Bytesize="4" Description="count_sword" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1324" Vartype="4 Bytes" Bytesize="4" Description="count_leather" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1328" Vartype="4 Bytes" Bytesize="4" Description="count_armor" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1332" Vartype="4 Bytes" Bytesize="4" RLECount="1761" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8376" Vartype="4 Bytes" Bytesize="4" Description="count_e_archer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8380" Vartype="4 Bytes" Bytesize="4" Description="count_e_xbow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8384" Vartype="4 Bytes" Bytesize="4" Description="count_e_spearman" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8388" Vartype="4 Bytes" Bytesize="4" Description="count_e_pike" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8392" Vartype="4 Bytes" Bytesize="4" Description="count_e_mace" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8396" Vartype="4 Bytes" Bytesize="4" Description="count_e_sword" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8400" Vartype="4 Bytes" Bytesize="4" Description="count_e_knight" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8404" Vartype="4 Bytes" Bytesize="4" Description="count_e_ladder" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8408" Vartype="4 Bytes" Bytesize="4" Description="count_e_engineer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8412" Vartype="4 Bytes" Bytesize="4" RLECount="41" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8576" Vartype="4 Bytes" Bytesize="4" Description="current_population" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8580" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8584" Vartype="4 Bytes" Bytesize="4" Description="tax_setting" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8588" Vartype="Byte" Bytesize="1" Description="rations" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8588" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8589" Vartype="Byte" Bytesize="1" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8592" Vartype="4 Bytes" Bytesize="4" RLECount="26" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8696" Vartype="2 Bytes" Bytesize="2" Description="lord_uid" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8698" Vartype="Byte" Bytesize="1" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8700" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="8704" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8716" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="8720" Vartype="4 Bytes" Bytesize="4" RLECount="12" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8768" Vartype="Byte" Bytesize="1" Description="blessed_people" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8769" Vartype="Byte" Bytesize="1" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8771" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8772" Vartype="4 Bytes" Bytesize="4" RLECount="14" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8828" Vartype="Byte" Bytesize="1" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8830" Vartype="Byte" Bytesize="1" Description="blessed_people_duplicate_non_auth" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8831" Vartype="Byte" Bytesize="1" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8832" Vartype="4 Bytes" Bytesize="4" RLECount="9" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8868" Vartype="4 Bytes" Bytesize="4" Description="beer_percentage" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8872" Vartype="4 Bytes" Bytesize="4" RLECount="10" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8912" Vartype="4 Bytes" Bytesize="4" Description="count_inn" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8916" Vartype="4 Bytes" Bytesize="4" RLECount="469" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10792" Vartype="4 Bytes" Bytesize="4" Description="count_a_archer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10796" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10800" Vartype="4 Bytes" Bytesize="4" Description="count_a_slave" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10804" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10808" Vartype="4 Bytes" Bytesize="4" Description="count_a_slinger" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10812" Vartype="4 Bytes" Bytesize="4" RLECount="1043" DisplayMethod="Unsigned Integer"/>
      <Element Offset="14984" Vartype="Byte" Bytesize="1" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="14986" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="14988" Vartype="4 Bytes" Bytesize="4" RLECount="9" DisplayMethod="Unsigned Integer"/>
      <Element Offset="15024" Vartype="4 Bytes" Bytesize="4" Description="last_element" DisplayMethod="Unsigned Integer"/>
    </Elements>
  </Structure>
</Structures>