
<Structures>
  <Structure Name="PlayerData" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="96" Vartype="4 Bytes" Bytesize="4" Description="popularity" DisplayMethod="Unsigned Integer"/>
      <Element Offset="100" Vartype="4 Bytes" Bytesize="4" RLECount="212" DisplayMethod="Unsigned Integer"/>
      <Element Offset="948" Vartype="4 Bytes" Bytesize="4" Description="previous_popularity?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="952" Vartype="4 Bytes" Bytesize="4" RLECount="36" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1096" Vartype="4 Bytes" Bytesize="4" Description="gold_previous_month?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1100" Vartype="4 Bytes" Bytesize="4" RLECount="35" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1240" Vartype="4 Bytes" Bytesize="4" Description="count_wood" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1244" Vartype="4 Bytes" Bytesize="4" Description="count_hops" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1248" Vartype="4 Bytes" Bytesize="4" Description="count_stone" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1252" Vartype="4 Bytes" Bytesize="4" Description="count_good5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1256" Vartype="4 Bytes" Bytesize="4" Description="count_iron" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1260" Vartype="4 Bytes" Bytesize="4" Description="count_pitch" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1264" Vartype="4 Bytes" Bytesize="4" Description="count_good8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1268" Vartype="4 Bytes" Bytesize="4" Description="count_wheat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1272" Vartype="4 Bytes" Bytesize="4" Description="count_bread" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1276" Vartype="4 Bytes" Bytesize="4" Description="count_cheese" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1280" Vartype="4 Bytes" Bytesize="4" Description="count_meat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1284" Vartype="4 Bytes" Bytesize="4" Description="count_fruit" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1288" Vartype="4 Bytes" Bytesize="4" Description="count_beer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1292" Vartype="4 Bytes" Bytesize="4" Description="gold" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1296" Vartype="4 Bytes" Bytesize="4" Description="count_flour" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1300" Vartype="4 Bytes" Bytesize="4" Description="count_bow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1304" Vartype="4 Bytes" Bytesize="4" Description="count_xbow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1308" Vartype="4 Bytes" Bytesize="4" Description="count_spear" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1312" Vartype="4 Bytes" Bytesize="4" Description="count_pike" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1316" Vartype="4 Bytes" Bytesize="4" Description="count_mace" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1320" Vartype="4 Bytes" Bytesize="4" Description="count_sword" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1324" Vartype="4 Bytes" Bytesize="4" Description="count_leather" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1328" Vartype="4 Bytes" Bytesize="4" Description="count_armor" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1332" Vartype="4 Bytes" Bytesize="4" RLECount="1761" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8376" Vartype="4 Bytes" Bytesize="4" Description="count_e_archer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8380" Vartype="4 Bytes" Bytesize="4" Description="count_e_xbow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8384" Vartype="4 Bytes" Bytesize="4" Description="count_e_spearman" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8388" Vartype="4 Bytes" Bytesize="4" Description="count_e_pike" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8392" Vartype="4 Bytes" Bytesize="4" Description="count_e_mace" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8396" Vartype="4 Bytes" Bytesize="4" Description="count_e_sword" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8400" Vartype="4 Bytes" Bytesize="4" Description="count_e_knight" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8404" Vartype="4 Bytes" Bytesize="4" Description="count_e_ladder" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8408" Vartype="4 Bytes" Bytesize="4" Description="count_e_engineer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8412" Vartype="4 Bytes" Bytesize="4" RLECount="72" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8700" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="8704" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8716" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="8720" Vartype="4 Bytes" Bytesize="4" RLECount="37" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8868" Vartype="4 Bytes" Bytesize="4" Description="beer_percentage" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8872" Vartype="4 Bytes" Bytesize="4" RLECount="10" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8912" Vartype="4 Bytes" Bytesize="4" Description="count_inn" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8916" Vartype="4 Bytes" Bytesize="4" RLECount="469" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10792" Vartype="4 Bytes" Bytesize="4" Description="count_a_archer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10796" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10800" Vartype="4 Bytes" Bytesize="4" Description="count_a_slave" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10804" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10808" Vartype="4 Bytes" Bytesize="4" Description="count_a_slinger" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10812" Vartype="4 Bytes" Bytesize="4" RLECount="1029" DisplayMethod="Unsigned Integer"/>
      <Element Offset="15024" Vartype="4 Bytes" Bytesize="4" Description="last_element" DisplayMethod="Unsigned Integer"/>
    </Elements>
  </Structure>
</Structures>