
<Structures>
  <Structure Name="PlayerData" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" Description="popularity" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4" Vartype="4 Bytes" Bytesize="4" RLECount="212" DisplayMethod="Unsigned Integer"/>
      <Element Offset="852" Vartype="4 Bytes" Bytesize="4" Description="previous_popularity?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="856" Vartype="4 Bytes" Bytesize="4" RLECount="36" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1000" Vartype="4 Bytes" Bytesize="4" Description="gold_previous_month?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1004" Vartype="4 Bytes" Bytesize="4" RLECount="35" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1144" Vartype="4 Bytes" Bytesize="4" Description="count_wood" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1148" Vartype="4 Bytes" Bytesize="4" Description="count_hops" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1152" Vartype="4 Bytes" Bytesize="4" Description="count_stone" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1156" Vartype="4 Bytes" Bytesize="4" Description="count_good5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1160" Vartype="4 Bytes" Bytesize="4" Description="count_iron" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1164" Vartype="4 Bytes" Bytesize="4" Description="count_pitch" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1168" Vartype="4 Bytes" Bytesize="4" Description="count_good8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1172" Vartype="4 Bytes" Bytesize="4" Description="count_wheat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1176" Vartype="4 Bytes" Bytesize="4" Description="count_bread" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1180" Vartype="4 Bytes" Bytesize="4" Description="count_cheese" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1184" Vartype="4 Bytes" Bytesize="4" Description="count_meat" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1188" Vartype="4 Bytes" Bytesize="4" Description="count_fruit" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1192" Vartype="4 Bytes" Bytesize="4" Description="count_beer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1196" Vartype="4 Bytes" Bytesize="4" Description="gold" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1200" Vartype="4 Bytes" Bytesize="4" Description="count_flour" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1204" Vartype="4 Bytes" Bytesize="4" Description="count_bow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1208" Vartype="4 Bytes" Bytesize="4" Description="count_xbow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1212" Vartype="4 Bytes" Bytesize="4" Description="count_spear" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1216" Vartype="4 Bytes" Bytesize="4" Description="count_pike" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1220" Vartype="4 Bytes" Bytesize="4" Description="count_mace" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1224" Vartype="4 Bytes" Bytesize="4" Description="count_sword" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1228" Vartype="4 Bytes" Bytesize="4" Description="count_leather" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1232" Vartype="4 Bytes" Bytesize="4" Description="count_armor" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1236" Vartype="4 Bytes" Bytesize="4" RLECount="1761" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8280" Vartype="4 Bytes" Bytesize="4" Description="count_e_archer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8284" Vartype="4 Bytes" Bytesize="4" Description="count_e_xbow" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8288" Vartype="4 Bytes" Bytesize="4" Description="count_e_spearman" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8292" Vartype="4 Bytes" Bytesize="4" Description="count_e_pike" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8296" Vartype="4 Bytes" Bytesize="4" Description="count_e_mace" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8300" Vartype="4 Bytes" Bytesize="4" Description="count_e_sword" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8304" Vartype="4 Bytes" Bytesize="4" Description="count_e_knight" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8308" Vartype="4 Bytes" Bytesize="4" Description="count_e_ladder" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8312" Vartype="4 Bytes" Bytesize="4" Description="count_e_engineer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8316" Vartype="4 Bytes" Bytesize="4" RLECount="72" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8604" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="8608" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8620" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="8624" Vartype="4 Bytes" Bytesize="4" RLECount="37" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8772" Vartype="4 Bytes" Bytesize="4" Description="beer_percentage" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8776" Vartype="4 Bytes" Bytesize="4" RLECount="10" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8816" Vartype="4 Bytes" Bytesize="4" Description="count_inn" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8820" Vartype="4 Bytes" Bytesize="4" RLECount="469" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10696" Vartype="4 Bytes" Bytesize="4" Description="count_a_archer" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10700" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10704" Vartype="4 Bytes" Bytesize="4" Description="count_a_slave" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10708" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10712" Vartype="4 Bytes" Bytesize="4" Description="count_a_slinger" DisplayMethod="Unsigned Integer"/>
      <Element Offset="10716" Vartype="4 Bytes" Bytesize="4" RLECount="1029" DisplayMethod="Unsigned Integer"/>
      <Element Offset="14832" Vartype="4 Bytes" Bytesize="4" Description="last_element" DisplayMethod="Unsigned Integer"/>
    </Elements>
  </Structure>
</Structures>