
<Structures>
  <Structure Name="Unit" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4" Vartype="4 Bytes" Bytesize="4" Description="animation_frame" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="20" Vartype="2 Bytes" Bytesize="2" RLECount="12" DisplayMethod="Unsigned Integer"/>
      <Element Offset="44" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="52" Vartype="4 Bytes" Bytesize="4" Description="unit_selected" DisplayMethod="Unsigned Integer"/>
      <Element Offset="56" Vartype="4 Bytes" Bytesize="4" Description="health_percentage_displayed" DisplayMethod="Unsigned Integer"/>
      <Element Offset="60" Vartype="4 Bytes" Bytesize="4" Description="time_alive_1" DisplayMethod="Unsigned Integer"/>
      <Element Offset="64" Vartype="4 Bytes" Bytesize="4" Description="time_alive_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="68" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="72" Vartype="4 Bytes" Bytesize="4" Description="animation_frame_standing_sitting_horse" DisplayMethod="Unsigned Integer"/>
      <Element Offset="76" Vartype="4 Bytes" Bytesize="4" RLECount="12" DisplayMethod="Unsigned Integer"/>
      <Element Offset="124" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="128" Vartype="4 Bytes" Bytesize="4" Description="owner" DisplayMethod="Unsigned Integer"/>
      <Element Offset="132" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="140" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="142" Vartype="2 Bytes" Bytesize="2" Description="unit_type" DisplayMethod="Unsigned Integer"/>
      <Element Offset="144" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="148" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="152" Vartype="4 Bytes" Bytesize="4" RLECount="6" DisplayMethod="Unsigned Integer"/>
      <Element Offset="176" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="178" Vartype="2 Bytes" Bytesize="2" Description="unit_selected" DisplayMethod="Unsigned Integer"/>
      <Element Offset="180" Vartype="2 Bytes" Bytesize="2" RLECount="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="196" Vartype="2 Bytes" Bytesize="2" Description="location_j" DisplayMethod="Unsigned Integer"/>
      <Element Offset="198" Vartype="2 Bytes" Bytesize="2" Description="location_i" DisplayMethod="Unsigned Integer"/>
      <Element Offset="200" Vartype="2 Bytes" Bytesize="2" Description="destination_location_j" DisplayMethod="Unsigned Integer"/>
      <Element Offset="202" Vartype="2 Bytes" Bytesize="2" Description="destination_location_i" DisplayMethod="Unsigned Integer"/>
      <Element Offset="204" Vartype="2 Bytes" Bytesize="2" Description="previous_location_j" DisplayMethod="Unsigned Integer"/>
      <Element Offset="206" Vartype="2 Bytes" Bytesize="2" Description="previous_location_i" DisplayMethod="Unsigned Integer"/>
      <Element Offset="208" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="212" Vartype="4 Bytes" Bytesize="4" Description="location_tile_index" DisplayMethod="Unsigned Integer"/>
      <Element Offset="216" Vartype="4 Bytes" Bytesize="4" Description="destination_location_tile_index" DisplayMethod="Unsigned Integer"/>
      <Element Offset="220" Vartype="4 Bytes" Bytesize="4" Description="previous_location_tile_index" DisplayMethod="Unsigned Integer"/>
      <Element Offset="224" Vartype="2 Bytes" Bytesize="2" Description="location_j_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="226" Vartype="2 Bytes" Bytesize="2" Description="location_i_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="228" Vartype="4 Bytes" Bytesize="4" Description="location_tile_index_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="232" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="236" Vartype="2 Bytes" Bytesize="2" Description="destination_location_j_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="238" Vartype="2 Bytes" Bytesize="2" Description="destination_location_i_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="240" Vartype="2 Bytes" Bytesize="2" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="246" Vartype="2 Bytes" Bytesize="2" Description="if_moving_is_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="248" Vartype="2 Bytes" Bytesize="2" Description="changes_when_moving_0_7_tile_tracker?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="250" Vartype="2 Bytes" Bytesize="2" Description="current_point_in_path_plan" DisplayMethod="Unsigned Integer"/>
      <Element Offset="252" Vartype="2 Bytes" Bytesize="2" Description="size_of_path_plan" DisplayMethod="Unsigned Integer"/>
      <Element Offset="254" Vartype="Byte" Bytesize="1" Description="direction_to_move_to_in_3_degrees_steps_from_map_north_clockwise" DisplayMethod="Unsigned Integer"/>
      <Element Offset="255" Vartype="Byte" Bytesize="1" RLECount="28" DisplayMethod="Unsigned Integer"/>
      <Element Offset="282" Vartype="Byte" Bytesize="1" RLECount="230" DisplayMethod="Unsigned Integer"/>
      <Element Offset="512" Vartype="4 Bytes" Bytesize="4" RLECount="41" DisplayMethod="Unsigned Integer"/>
      <Element Offset="676" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="680" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="684" Vartype="2 Bytes" Bytesize="2" Description="total_health?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="686" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="688" Vartype="4 Bytes" Bytesize="4" Description="animation_timer?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="692" Vartype="4 Bytes" Bytesize="4" RLECount="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="724" Vartype="2 Bytes" Bytesize="2" Description="health_2?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="726" Vartype="2 Bytes" Bytesize="2" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="732" Vartype="2 Bytes" Bytesize="2" Description="planned_destination_j_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="734" Vartype="2 Bytes" Bytesize="2" Description="planned_destination_i_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="736" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="740" Vartype="4 Bytes" Bytesize="4" RLECount="25" DisplayMethod="Unsigned Integer"/>
      <Element Offset="840" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="844" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="848" Vartype="4 Bytes" Bytesize="4" Description="time_alive_1" DisplayMethod="Unsigned Integer"/>
      <Element Offset="852" Vartype="4 Bytes" Bytesize="4" Description="time_alive_2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="856" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="860" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="876" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="880" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="888" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="890" Vartype="2 Bytes" Bytesize="2" Description="animation_timer_2?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="892" Vartype="2 Bytes" Bytesize="2" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="900" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="904" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="908" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="912" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="916" Vartype="4 Bytes" Bytesize="4" RLECount="6" DisplayMethod="Unsigned Integer"/>
      <Element Offset="940" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="944" Vartype="4 Bytes" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="964" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="968" Vartype="4 Bytes" Bytesize="4" Description="health" DisplayMethod="Unsigned Integer"/>
      <Element Offset="972" Vartype="4 Bytes" Bytesize="4" Description="hitpoints" DisplayMethod="Unsigned Integer"/>
      <Element Offset="976" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="988" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="992" Vartype="4 Bytes" Bytesize="4" RLECount="16" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1056" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1060" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1076" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1080" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1088" Vartype="4 Bytes" Bytesize="4" Description="alive_timer_3?" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1092" Vartype="2 Bytes" Bytesize="2" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1096" Vartype="4 Bytes" Bytesize="4" RLECount="7" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1124" Vartype="2 Bytes" Bytesize="2" DisplayMethod="Unsigned Integer"/>
    </Elements>
  </Structure>
</Structures>